version: "3.8"
services:
  client:
    image: server:latest
    stdin_open: true
    volumes:
      - "/myapp/node_modules"
      - "./:/myapp"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"