version: "3.8"
services:
  db: 
    image: ""
    volumes: ""
  backend:
    image: backend:latest
    stdin_open: true
    volumes:
      - "/backend/node_modules"
      - "./:/backend"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"