version: "3.8"
services:
  backend:
    image: backend:latest
    stdin_open: true
    volumes:
      - "/myapp/backend/node_modules"
      - "./myapp/backend"
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"